# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ce14b51dcae30ed0c9d3014bda2e66af0dc8beb02cb1d87bbae795aff1b2005e5d5d87778cba5823c6377e11fee0d413fc1364ec9448c3cb55e0747aede1ad

test:
  secret_key_base: fa644bc28c0f0002cb903442ae0c8cbe0d4e82a604ea780259a0fc4792ae80c18c3e757e57a8d3c151f1f1840d04d6500dd4259118ecd8e1cdbd6eb7db4a63a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
